asignacion_horario/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("parametros.urls")),
    url(r'^',include("horario.urls")),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

horario/urls.py
from django.conf.urls import url
from .views import (PeriodoProfesorModuloListView,
        PeriodoProfesorModuloCreateView,
        PeriodoProfesorModuloUpdateView,
        PeriodoProfesorModuloDeleteView,

        #params
        GetPlan,
        GetPeriodo,
        GetProfesor,
        GetModulo,
        GetCarrera,
        GetActividad,
        SaveActividadBloque,
        GetValidaPpm,

        SaveHorarioProtegido,
        deleteHorarioTemp,

        # HorarioView,
        HorarioTemplateView,
        HorarioSave,
        saveHorario,
        HorarioListView,
        ReservaBloqueProtegidoListView,
        ReservaBloqueProtegidoCreateView,
        ReservaBloqueProtegidoUpdateView,
        ReservaBloqueProtegidoDeleteView,

        #CursosGrupo
        CursosGrupoListView,
        CursosGrupoCreateView,
        CursosGrupoUpdateView,
        CursosGrupoDeleteView,
        saveCursosGrupo,
        GetModuloEspejoGruposCurso,
        )

urlpatterns = [
        #Periodo Profesor Modulo
        url(r'^periodoprofesormodulo/$', PeriodoProfesorModuloListView.as_view(), name='periodoprofesormodulo'),
        url(r'^periodoprofesormodulo/add/$', PeriodoProfesorModuloCreateView.as_view(), name='periodoprofesormodulo-add'),
        url(r'^periodoprofesormodulo/edit/(?P<pk>\d+)/$', PeriodoProfesorModuloUpdateView.as_view(), name='periodoprofesormodulo-edit'),
        url(r'^periodoprofesormodulo/(?P<pk>\d+)/delete/$', PeriodoProfesorModuloDeleteView.as_view(), name='periodoprofesormodulo-delete'),
        #Reserva Bloque Protegido
        url(r'^reservabloqueprotegido/$', ReservaBloqueProtegidoListView.as_view(), name='reservabloqueprotegido'),
        url(r'^reservabloqueprotegido/save/$', SaveHorarioProtegido, name='save-reservabloqueprotegido'),
        url(r'^reservabloqueprotegido/add/$', ReservaBloqueProtegidoCreateView.as_view(), name='reservabloqueprotegido-add'),
        # url(r'^reservabloqueprotegido/edit/(?P<pk>\d+)/$', ReservaBloqueProtegidoUpdateView.as_view(), name='reservabloqueprotegido-edit'),
        url(r'^reservabloqueprotegido/(?P<pk>\d+)/delete/$', ReservaBloqueProtegidoDeleteView.as_view(), name='reservabloqueprotegido-delete'),
        #Horario
        url(r'^horario/$', HorarioListView.as_view(), name='horario'),
        url(r'^horario/edit/$', HorarioTemplateView.as_view(), name='horario-edit'),
        #url(r'^horario/save/$', HorarioSave, name='horario-save'),
        url(r'^horario/save/$', saveHorario, name='horario-save'),
        #url(r'^horario/saveActividadBloque/$', SaveActividadBloque, name='actividadbloque-save'),
        #CursosGrupo
        url(r'^cursosgrupo/$', CursosGrupoListView.as_view(), name='cursosgrupo'),
        url(r'^cursosgrupo/add/$', CursosGrupoCreateView.as_view(), name='cursosgrupo-add'),
        url(r'^cursosgrupo/edit/(?P<pk>\d+)/$', CursosGrupoUpdateView.as_view(), name='cursosgrupo-edit'),
        url(r'^cursosgrupo/(?P<pk>\d+)/delete/$', CursosGrupoDeleteView.as_view(), name='cursosgrupo-delete'),

        #Param
        url(r'^horario/param/get_plan/$', GetPlan, name='get-plan'),
        url(r'^horario/param/get_periodo/$', GetPeriodo, name='get-periodo'),
        url(r'^horario/param/get_profesor/$', GetProfesor, name='get-periodo'),
        url(r'^horario/param/get_modulo/$', GetModulo, name='get-modulo'),
        url(r'^horario/param/get_carrera/$', GetCarrera, name='get-carrera'),
        url(r'^horario/param/get_actividad/$', GetActividad, name='get-actividad'),

        #CursosGrupo
        url(r'^horario/param/get_carrera-cg/$', GetCarrera, name='get-carrera-cg'),
        url(r'^horario/param/get_plan-cg/$', GetPlan, name='get-plan-cg'),
        url(r'^horario/param/get_modulo-cg/$', GetModulo, name='get-modulo-cg'),
        url(r'^horario/cg/save/$', saveCursosGrupo, name='cursos-grupo-save'),

        #CursosGrupo y Espejo
        url(r'^horario/param/get_modulo_espejo_cursos_grupo/$',
            GetModuloEspejoGruposCurso, name='get-espejo-cg'),

        #validaciones
        url(r'^horario/horario/get_valida_ppm/$', GetValidaPpm, name='get-valida-ppm'),

        #delete Temp
        url(r'^horario/horario/delete_horario_temp/$', deleteHorarioTemp, name='delete-horariotemp'),
        ]

parametros/urls.py
from django.conf.urls import url
from .views import (
    CarreraView,
    CarreraCreateView,
    CarreraUpdateView,
    CarreraDeleteView,
    PlanView,
    PlanCreateView,
    PlanUpdateView,
    PlanDeleteView,
    ModuloView,
    ModuloCreateView,
    ModuloUpdateView,
    ModuloDeleteView,
    DepartamentoView,
    DepartamentoCreateView,
    DepartamentoUpdateView,
    DepartamentoDeleteView,
    AnioView,
    AnioCreateView,
    AnioUpdateView,
    AnioDeleteView,
    PeriodoView,
    PeriodoCreateView,
    PeriodoUpdateView,
    PeriodoDeleteView,
    BloqueView,
    BloqueCreateView,
    BloqueUpdateView,
    BloqueDeleteView,
    ProfesorView,
    ProfesorUpdateView,
    ProfesorCreateView,
    ProfesorDeleteView,
    SemestreView,
    SemestreCreateView,
    SemestreUpdateView,
    SemestreDeleteView,
    ActividadView,
    ActividadCreateView,
    ActividadUpdateView,
    ActividadDeleteView,
    ModuloEspejoView,
    ModuloEspejoCreateView,
    ModuloEspejoUpdateView,
    ModuloEspejoDeleteView,
    saveModuloEspejo,
    GetDataModuloEspejo,
    LogoutView,
    LoginView,
    )

urlpatterns = [
    #carrera
    url(r'^carrera/$', CarreraView.as_view(), name='carrera-list'),
    url(r'^carrera/add/$', CarreraCreateView.as_view(), name='carrera-add'),
    url(r'^carrera/edit/(?P<pk>\d+)/$', CarreraUpdateView.as_view(), name='carrera-edit'),
    url(r'^carrera/(?P<pk>\d+)/delete/$', CarreraDeleteView.as_view(), name='carrera-delete'),
    #plan
    url(r'^plan/$', PlanView.as_view(), name='plan-list'),
    url(r'^plan/add/$', PlanCreateView.as_view(), name='plan-add'),
    url(r'^plan/edit/(?P<pk>\d+)/$', PlanUpdateView.as_view(), name='plan-edit'),
    url(r'^plan/(?P<pk>\d+)/delete/$', PlanDeleteView.as_view(), name='plan-delete'),
    #modulo
    url(r'^modulo/$', ModuloView.as_view(), name='modulo-list'),
    url(r'^modulo/add/$', ModuloCreateView.as_view(), name='modulo-add'),
    url(r'^modulo/edit/(?P<pk>\d+)/$', ModuloUpdateView.as_view(), name='modulo-edit'),
    url(r'^modulo/(?P<pk>\d+)/delete/$', ModuloDeleteView.as_view(), name='modulo-delete'),
    #departamento
    url(r'^departamento/$', DepartamentoView.as_view(), name='departamento-list'),
    url(r'^departamento/add/$', DepartamentoCreateView.as_view(), name='departamento-add'),
    url(r'^departamento/edit/(?P<pk>\d+)/$', DepartamentoUpdateView.as_view(), name='departamento-edit'),
    url(r'^departamento/(?P<pk>\d+)/delete/$', DepartamentoDeleteView.as_view(), name='departamento-delete'),
    #año
    url(r'^anio/$', AnioView.as_view(), name='anio-list'),
    url(r'^anio/add/$', AnioCreateView.as_view(), name='anio-add'),
    url(r'^anio/edit/(?P<pk>\d+)/$', AnioUpdateView.as_view(), name='anio-edit'),
    url(r'^anio/(?P<pk>\d+)/delete/$', AnioDeleteView.as_view(), name='anio-delete'),
    #Periodo
    url(r'^periodo/$', PeriodoView.as_view(), name='periodo-list'),
    url(r'^periodo/add/$', PeriodoCreateView.as_view(), name='periodo-add'),
    url(r'^periodo/edit/(?P<pk>\d+)/$', PeriodoUpdateView.as_view(), name='periodo-edit'),
    url(r'^periodo/(?P<pk>\d+)/delete/$', PeriodoDeleteView.as_view(), name='periodo-delete'),
    #bloque
    url(r'^bloque/$', BloqueView.as_view(), name='bloque-list'),
    url(r'^bloque/add/$', BloqueCreateView.as_view(), name='bloque-add'),
    url(r'^bloque/edit/(?P<pk>\d+)/$', BloqueUpdateView.as_view(), name='bloque-edit'),
    url(r'^bloque/(?P<pk>\d+)/delete/$', BloqueDeleteView.as_view(), name='bloque-delete'),
    #profesor
    url(r'^profesor/$', ProfesorView.as_view(), name='profesor-list'),
    url(r'^profesor/add/$', ProfesorCreateView.as_view(), name='profesor-add'),
    url(r'^profesor/edit/(?P<pk>\d+)/$', ProfesorUpdateView.as_view(), name='profesor-edit'),
    url(r'^profesor/(?P<pk>\d+)/delete/$', ProfesorDeleteView.as_view(), name='profesor-delete'),
    #semestre
    url(r'^semestre/$', SemestreView.as_view(), name='semestre-list'),
    url(r'^semestre/add/$', SemestreCreateView.as_view(), name='semestre-add'),
    url(r'^semestre/edit/(?P<pk>\d+)/$', SemestreUpdateView.as_view(), name='semestre-edit'),
    url(r'^semestre/(?P<pk>\d+)/delete/$', SemestreDeleteView.as_view(), name='semestre-delete'),
    #actividad
    url(r'^actividad/$', ActividadView.as_view(), name='actividad-list'),
    url(r'^actividad/add/$', ActividadCreateView.as_view(), name='actividad-add'),
    url(r'^actividad/edit/(?P<pk>\d+)/$', ActividadUpdateView.as_view(), name='actividad-edit'),
    url(r'^actividad/(?P<pk>\d+)/delete/$', ActividadDeleteView.as_view(), name='actividad-delete'),
    #moduloespejo
    url(r'^moduloespejo/$', ModuloEspejoView.as_view(), name='moduloespejo-list'),
    url(r'^moduloespejo/add/$', ModuloEspejoCreateView.as_view(), name='moduloespejo-add'),
    url(r'^moduloespejo/edit/(?P<pk>\d+)/$', ModuloEspejoUpdateView.as_view(), name='moduloespejo-edit'),
    url(r'^moduloespejo/(?P<pk>\d+)/delete/$', ModuloEspejoDeleteView.as_view(), name='moduloespejo-delete'),
    url(r'^param/get_data_moduloespejo/$', GetDataModuloEspejo, name='get-param-moduloespejo'),
    url(r'^param/save_moduloespejo/$', saveModuloEspejo, name='save-moduloespejo'),
    #logout
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),

] 

parametros/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Carrera(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField (max_length=200, blank=True, null=True)

    def __str__(self):
        return self.nombre

class Plan(models.Model):
    nombre = models.CharField(max_length=10)
    carrera = models.ForeignKey(Carrera, null=True)

    class Meta:
        ordering = ["-id"]


    def __str__(self):
        return "%s" %(self.nombre)


class Semestre(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre


class Modulo(models.Model):
    nombre = models.CharField(u'Modulo', max_length=100)
    carrera = models.ForeignKey(Carrera, default='')
    semestre = models.ForeignKey(Semestre)
    plan = models.ForeignKey(Plan)
    creditos = models.IntegerField(u'Créditos', default=0)
    horas_clase = models.IntegerField(u'Horas de clase', default=0)
    horas_seminario = models.IntegerField(u'Horas de seminario',default=0)
    horas_laboratorio = models.IntegerField(u'horas de laboratorio', default=0)
    horas_taller = models.IntegerField(u'Horas de Taller', default=0)
    horas_ayudantia = models.IntegerField(u'Horas de Ayudantía', default=0)

    def __str__ (self):
        return ("%s del %s")%(self.nombre, self.plan.nombre)


class Departamento(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(u'Descripción', max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Profesor(models.Model):
    nombre = models.CharField(max_length=100)
    departamento = models.ForeignKey(Departamento)
    rut = models.CharField(u'RUT', max_length=12, default='')
    correo = models.EmailField('Correo Electrónico', max_length=100, default='')

    def __str__(self):
        return self.nombre


class Anio(models.Model):
    nombre = models.CharField(max_length=4)

    class Meta:
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre


class Periodo(models.Model):
    nombre = models.CharField(max_length=50)
    anio = models.ForeignKey(Anio, null=True)

    class Meta:
        ordering = ["-nombre"]


    def __str__(self):
        return "%s del año %s"%(self.nombre,
                                self.anio.nombre)


class Bloque(models.Model):
    nombre = models.IntegerField(validators=[MaxValueValidator(15),
                                        MinValueValidator(1)],
                                default=0,
                                help_text="""<sup>Indique un número entre 1 y 15
                                        para identificar el bloque</sup>""",
                                )
    hora_inicio = models.TimeField(u'Hora Inicio', default="00:00")
    hora_termino = models.TimeField(u'Hora de Termino', default="00:00")


    class Meta:
        ordering = ["nombre"]


    def __str__(self):
        return "número: %(nombre)s "%{"nombre":self.nombre}


class Actividad(models.Model):
    nombre = models.CharField(max_length=50)
    identificador = models.CharField(max_length=1,
                    help_text="<sup>Escriba una letra para identifique la actividad</sup>",
                    default = "",
                    unique = True,
                    )

    def __str__(self):
        return self.nombre


class ModuloEspejo(models.Model):
    # carrera = models.ForeignKey(Carrera, default=None)
    # plan = models.ForeignKey(Plan, default=None)
    modulo = models.ForeignKey(Modulo, default=None)
    espejo = models.ForeignKey(Modulo, related_name='+')

    def __str__(self):
        msj = "El modulo %(modulo)s es espejo de %(espejo)s"%{
                                    "modulo":self.modulo,
                                    "espejo":self.espejo,
                                    }
        return msj

templates/parametros/actividad.html
{% block content %}

<div class="row">

	<div class="col-lg-12">
		<div class="header">
			<h4>{{ titulo|upper }}</h4>
		    <p></p>
		    <button class="btn btn-success add">Nuevo</button>
		    </div>
	    </div>
    </div>

	<div class="col-lg-12">
	    <p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
            	Listado de {{ titulo }}
            </div>
        	<!-- /.panel-heading -->
            <div class="panel-body">
		    	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead class="thead-default">
						<tr>
		      				<th>Nombre</th>
		      				<th>Descripción</th>
							<th></th>
							<th></th>
        				</tr>
        			</thead>
					<tbody>
					{% for obj in object_list %}
						<tr>
							<td>{{ obj.nombre }}</td>
							<td>{{ obj.identificador }}</td>
							<td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs edit" data-title="Edit" data-toggle="modal" data-target="#edit" value="{{ obj.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
							<td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs delete" data-title="Delete" data-toggle="modal" data-target="#delete" value="{{ obj.id }}"><span class="glyphicon glyphicon-trash"></span></button></p></td>
						</tr>
					{% endfor %}
					</tbody>
                </table>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


{% endblock %}

templates/parametros/bloque.html
{% block content %}

<div class="row">

	<div class="col-lg-12">
		<div class="header">
			<h4>{{ titulo|upper }}</h4>
		    <p></p>
		    <button class="btn btn-success add">Nuevo</button>
		    </div>
	    </div>
    </div>

	<div class="col-lg-12">
	    <p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
            	Listado de {{ titulo }}
            </div>
        	<!-- /.panel-heading -->
            <div class="panel-body">
		    	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead class="thead-default">
						<tr>
		      				<th>Bloque</th>
						    <th>Inicio</th>
						    <th>Termino</th>
							<th></th>
							<th></th>
        				</tr>
        			</thead>
					<tbody>
					{% for obj in object_list %}
						<tr>
							<td>{{ obj.nombre }}</td>
						    <td>{{ obj.hora_inicio }}</td>
						    <td>{{ obj.hora_termino }}</td>
							<td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs edit" data-title="Edit" data-toggle="modal" data-target="#edit" value="{{ obj.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
							<td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs delete" data-title="Delete" data-toggle="modal" data-target="#delete" value="{{ obj.id }}"><span class="glyphicon glyphicon-trash"></span></button></p></td>
						</tr>
					{% endfor %}
					</tbody>
                </table>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


{% endblock %}

templates/parametros/elimina.html
{% extends "base.html" %}

{% block content %}
</br>
<h2>¿SEGURO QUE QUIERES BORRAR {{ object.module }}?</h2>
</br>

<h3>{{ object.nombre }}</h3>
</br>
</br>


<form method="POST" action="" class="form-inline">
	{% csrf_token %}
<input type="submit" value="Confirmar" />
<a href="#" class="button confirm-delete">Cancelar</a>
</form>
{% endblock %}

templates/parametros/form.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}

{% endblock %}

{% block content %}


  {% if messages %}

  <div class="alert alert-info alert-dismissable">
    {% for message in messages %}
      {{ message }}
    {% endfor %}

  </div>
  {% endif %}

<fieldset>
    <legend>{{ titulo }}</legend>
</fieldset>
<br>

<form id="form" role="form" class="form-horizontal" method="post">
    {% csrf_token %}

    {% bootstrap_form form layout="horizontal" %}

    {% buttons layout='horizontal'%}
    <div class="submit-row">
        <div class="btn-group btn-group-md btn-block">
        {% if save_addanother %}
        <button type="submit" class="btn btn-primary save-addanother" name="_addanother">
            <span class="glyphicon glyphicon-save"></span>
            Guardar y añadir otro
        </button>
        {% endif %}

        <button type="submit" name="_save" class="btn btn-primary">
            <span class="glyphicon glyphicon-saved"></span>
            Guardar
        </button>

        <button type="reset" class="btn btn-danger reset">
            <span class="glyphicon glyphicon-remove"></span>
             Cancelar
        </button>

        </div>
    </div>

    {% endbuttons %}
</form>

{% if save_addanother %}
<div class="container">
    <div class="row">
        <table id="save-dataform" class="table">
        </table>
    </div>
</div>
{% endif %}

{% endblock %}

templates/parametros/form_moduloespejo.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}

{% endblock %}

{% block content %}


{% if messages %}

<div class="alert alert-info alert-dismissable">
  {% for message in messages %}
    {{ message }}
  {% endfor %}

</div>
{% endif %}

<fieldset>
    <legend>{{ titulo }}</legend>
</fieldset>
<p></p>

<form id="form" role="form" class="form-horizontal" method="post">
  {% csrf_token %}

  <div class="form-group">
    <label class="col-md-3 control-label" for="id_carrera">Carrera</label>
    <div class="col-md-9">
      <select class="form-control" id="carrera" name="carrera" title="" required="">
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="plan">Plan</label>
    <div class="col-md-9">
      <select class="form-control" id="plan" name="plan" title="" required="">
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="col-md-3 control-label" for="modulo">Modulo</label>
    <div class="col-md-9">
      <select class="form-control" id="modulo" name="modulo" title="" required="">
      </select>
    </div>
  </div>

  {% include "parametros/tabla_moduloespejo.html" %}


  {% buttons layout='horizontal'%}
  <div class="submit-row">
    <div class="btn-group btn-block">
      {% if save_addanother %}
      <button type="submit" class="btn btn-primary save-addanother" name="_addanother">
        <span class="glyphicon glyphicon-save"></span>
          Guardar y añadir otro
      </button>
      {% endif %}

      <button type="submit" name="_save" class="btn btn-primary">
          <span class="glyphicon glyphicon-saved"></span>
          Guardar
      </button>

      <button type="reset" class="btn btn-danger reset">
        <span class="glyphicon glyphicon-remove"></span>
         Cancelar
      </button>
    </div>
  </div>
  {% endbuttons %}
</form>

<script src="/static/js/utils.js"></script>
<script src="/static/js/modulo-espejo.js"></script>

{% endblock %}

templates/parametros/maestro.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}

{% endblock %}



{% block content %}

  {% if confirm %}
  <div class="alert alert-info alert-dismissable">
    {{ confirm }}
  </div>
  {% endif %}

  {% if messages %}

  <div class="alert alert-info alert-dismissable">
    {% for message in messages %}
      {{ message }}
    {% endfor %}

  </div>
  {% endif %}


    {% if titulo == 'Carreras' or titulo == 'Departamentos' %}
      {% include "parametros/maestro_generico.html" %}
    {% endif %}

    {% if titulo == 'Planes' %}
        {% include "parametros/plan.html" %}
    {% endif %}

    {% if titulo == 'Modulos' %}
        {% include 'parametros/modulo.html' %}
    {% endif %}

    {% if titulo == 'Años' %}
        {% include 'parametros/anio.html' %}
    {% endif %}

    {% if titulo == 'Bloques' %}
        {% include 'parametros/bloque.html' %}
    {% endif %}

    {% if titulo == 'Periodos' %}
        {% include 'parametros/periodo.html' %}
    {% endif %}

    {% if titulo == 'Profesores' %}
        {% include 'parametros/profesor.html' %}
    {% endif %}

    {% if titulo == 'Semestres' %}
        {% include 'parametros/semestre.html' %}
    {% endif %}

    {% if titulo == 'Actividades' %}
        {% include 'parametros/actividad.html' %}
    {% endif %}

    {% if titulo == 'Módulo Espejo' %}
        {% include 'parametros/modulo_espejo.html' %}
    {% endif %}

<!-- end container -->

{% endblock %}

templates/parametros/maestro_generico.html
{% block content %}

<div class="row">

	<div class="col-lg-12">
		<div class="header">
			<h4>{{ titulo|upper }}</h4>
		    <p></p>
		    <button class="btn btn-success add">Nuevo</button>
		    </div>
	    </div>
    </div>

	<div class="col-lg-12">
	    <p></p>
		<div class="panel panel-default">
			<div class="panel-heading">
            	Listado de {{ titulo }}
            </div>
        	<!-- /.panel-heading -->
            <div class="panel-body">
		    	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead class="thead-default">
						<tr>
		      				<th>Nombre</th>
		      				<th>Descripción</th>
							<th></th>
							<th></th>
        				</tr>
        			</thead>
					<tbody>
					{% for obj in object_list %}
						<tr>
							<td>{{ obj.nombre }}</td>
							<td>{{ obj.descripcion }}</td>
							<td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs edit" data-title="Edit" data-toggle="modal" data-target="#edit" value="{{ obj.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
							<td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs delete" data-title="Delete" data-toggle="modal" data-target="#delete" value="{{ obj.id }}"><span class="glyphicon glyphicon-trash"></span></button></p></td>
						</tr>
					{% endfor %}
					</tbody>
                </table>
                <!-- /.table-responsive -->

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


{% endblock %}

templates/parametros/maestro_single.html
{% block content %}
    <fieldset>
      <legend>Listado de {{ titulo }}</legend>
      <table class="table">
        <thead class="thead-default">
        <tr>
          <th>#</th>
          <th>Nombre</th>
        </tr>
        </thead>
        {% for obj in object_list %}
        <tbody>
          <tr>
            <th scope="row">{{ obj.id }}</th>
            <td>{{ obj.nombre }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </fieldset>

{% endblock %}