asignacion_horario/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("parametros.urls")),
    url(r'^',include("horario.urls")),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

horario/urls.py
from django.conf.urls import url
from .views import (PeriodoProfesorModuloListView,
        PeriodoProfesorModuloCreateView,
        PeriodoProfesorModuloUpdateView,
        PeriodoProfesorModuloDeleteView,

        #params
        GetPlan,
        GetPeriodo,
        GetProfesor,
        GetModulo,
        GetCarrera,
        GetActividad,
        SaveActividadBloque,
        GetValidaPpm,

        SaveHorarioProtegido,
        deleteHorarioTemp,

        # HorarioView,
        HorarioTemplateView,
        HorarioSave,
        saveHorario,
        HorarioListView,
        ReservaBloqueProtegidoListView,
        ReservaBloqueProtegidoCreateView,
        ReservaBloqueProtegidoUpdateView,
        ReservaBloqueProtegidoDeleteView,

        #CursosGrupo
        CursosGrupoListView,
        CursosGrupoCreateView,
        CursosGrupoUpdateView,
        CursosGrupoDeleteView,
        saveCursosGrupo,
        GetModuloEspejoGruposCurso,
        )

urlpatterns = [
        #Periodo Profesor Modulo
        url(r'^periodoprofesormodulo/$', PeriodoProfesorModuloListView.as_view(), name='periodoprofesormodulo'),
        url(r'^periodoprofesormodulo/add/$', PeriodoProfesorModuloCreateView.as_view(), name='periodoprofesormodulo-add'),
        url(r'^periodoprofesormodulo/edit/(?P<pk>\d+)/$', PeriodoProfesorModuloUpdateView.as_view(), name='periodoprofesormodulo-edit'),
        url(r'^periodoprofesormodulo/(?P<pk>\d+)/delete/$', PeriodoProfesorModuloDeleteView.as_view(), name='periodoprofesormodulo-delete'),
        #Reserva Bloque Protegido
        url(r'^reservabloqueprotegido/$', ReservaBloqueProtegidoListView.as_view(), name='reservabloqueprotegido'),
        url(r'^reservabloqueprotegido/save/$', SaveHorarioProtegido, name='save-reservabloqueprotegido'),
        url(r'^reservabloqueprotegido/add/$', ReservaBloqueProtegidoCreateView.as_view(), name='reservabloqueprotegido-add'),
        # url(r'^reservabloqueprotegido/edit/(?P<pk>\d+)/$', ReservaBloqueProtegidoUpdateView.as_view(), name='reservabloqueprotegido-edit'),
        url(r'^reservabloqueprotegido/(?P<pk>\d+)/delete/$', ReservaBloqueProtegidoDeleteView.as_view(), name='reservabloqueprotegido-delete'),
        #Horario
        url(r'^horario/$', HorarioListView.as_view(), name='horario'),
        url(r'^horario/edit/$', HorarioTemplateView.as_view(), name='horario-edit'),
        #url(r'^horario/save/$', HorarioSave, name='horario-save'),
        url(r'^horario/save/$', saveHorario, name='horario-save'),
        #url(r'^horario/saveActividadBloque/$', SaveActividadBloque, name='actividadbloque-save'),
        #CursosGrupo
        url(r'^cursosgrupo/$', CursosGrupoListView.as_view(), name='cursosgrupo'),
        url(r'^cursosgrupo/add/$', CursosGrupoCreateView.as_view(), name='cursosgrupo-add'),
        url(r'^cursosgrupo/edit/(?P<pk>\d+)/$', CursosGrupoUpdateView.as_view(), name='cursosgrupo-edit'),
        url(r'^cursosgrupo/(?P<pk>\d+)/delete/$', CursosGrupoDeleteView.as_view(), name='cursosgrupo-delete'),

        #Param
        url(r'^horario/param/get_plan/$', GetPlan, name='get-plan'),
        url(r'^horario/param/get_periodo/$', GetPeriodo, name='get-periodo'),
        url(r'^horario/param/get_profesor/$', GetProfesor, name='get-periodo'),
        url(r'^horario/param/get_modulo/$', GetModulo, name='get-modulo'),
        url(r'^horario/param/get_carrera/$', GetCarrera, name='get-carrera'),
        url(r'^horario/param/get_actividad/$', GetActividad, name='get-actividad'),

        #CursosGrupo
        url(r'^horario/param/get_carrera-cg/$', GetCarrera, name='get-carrera-cg'),
        url(r'^horario/param/get_plan-cg/$', GetPlan, name='get-plan-cg'),
        url(r'^horario/param/get_modulo-cg/$', GetModulo, name='get-modulo-cg'),
        url(r'^horario/cg/save/$', saveCursosGrupo, name='cursos-grupo-save'),

        #CursosGrupo y Espejo
        url(r'^horario/param/get_modulo_espejo_cursos_grupo/$',
            GetModuloEspejoGruposCurso, name='get-espejo-cg'),

        #validaciones
        url(r'^horario/horario/get_valida_ppm/$', GetValidaPpm, name='get-valida-ppm'),

        #delete Temp
        url(r'^horario/horario/delete_horario_temp/$', deleteHorarioTemp, name='delete-horariotemp'),
        ]

horario/models.py
#!/usr/bin/python3
from django.db import models
from parametros.models import (Periodo,
                             Profesor,
                             Modulo,
                             Bloque,
                             Carrera,
                             Plan,
                             Actividad,
                              )
# Create your models here.

class PeriodoProfesorModulo(models.Model):
    carrera = models.ForeignKey(Carrera, default=None)
    plan = models.ForeignKey(Plan, default=None)
    periodo = models.ForeignKey(Periodo, default=None)
    modulo = models.ForeignKey(Modulo, default=None)
    profesor = models.ForeignKey(Profesor, default=None)
    compartido = models.BooleanField(u'Cursos Grupos', default=False,
        help_text="<small>Check si el módulo será un curso compartido</small>",
        );

    def __str__(self):
        return ('%s %s %s')%(self.periodo, self.profesor, self.modulo)


class Horario(models.Model):
    periodoprofesormodulo = models.ForeignKey(PeriodoProfesorModulo)
    dia_semana = models.CharField(max_length=20, default="")
    reservado = models.BooleanField(default=False)
    bloque = models.ForeignKey(Bloque, default=None)
    actividad= models.ForeignKey(Actividad, default=None, null=True, blank=True)


class ReservaBloqueProtegido(models.Model):
    bloque = models.ForeignKey(Bloque, default=None)
    reservado = models.BooleanField(default=False)

    class Meta:
        ordering = ["bloque"]

class CursosGrupo(models.Model):
    # periodoprofesormodulo = models.ForeignKey(PeriodoProfesorModulo, default=None)
    periodo = models.ForeignKey(Periodo, default=None)
    modulo = models.ForeignKey(Modulo, default=None)
    curso_grupo = models.ForeignKey(Modulo, related_name='+', default=None)

    def __str__(self):
        return self.modulo.nombre


class HorarioTemp(models.Model):
    """
    Clase utilitaria para almacenar atributos temporales que pudiesen
    servir para implementar clases que dependen de acciones posteriores
    a fin de efectuarse de buena manera
    Clase pivot
    """
    dia_semana = models.CharField(max_length=20, default="", null=True)
    reservado = models.BooleanField(default=False)
    bloque = models.ForeignKey(Bloque, default=None, null=True)
    actividad= models.ForeignKey(Actividad, default=None, null=True)
    carrera = models.ForeignKey(Carrera, default=None, null=True)
    modulo = models.ForeignKey(Modulo, default=None, null=True)
    profesor = models.ForeignKey(Profesor, default=None, null=True)
    cursogrupo = models.ForeignKey(Modulo, related_name="+",
                        default=None, null=True)
    cursogrupoline = models.IntegerField(null=True, default=None)

parametros/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Carrera(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField (max_length=200, blank=True, null=True)

    def __str__(self):
        return self.nombre

class Plan(models.Model):
    nombre = models.CharField(max_length=10)
    carrera = models.ForeignKey(Carrera, null=True)

    class Meta:
        ordering = ["-id"]


    def __str__(self):
        return "%s" %(self.nombre)


class Semestre(models.Model):
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre


class Modulo(models.Model):
    nombre = models.CharField(u'Modulo', max_length=100)
    carrera = models.ForeignKey(Carrera, default='')
    semestre = models.ForeignKey(Semestre)
    plan = models.ForeignKey(Plan)
    creditos = models.IntegerField(u'Créditos', default=0)
    horas_clase = models.IntegerField(u'Horas de clase', default=0)
    horas_seminario = models.IntegerField(u'Horas de seminario',default=0)
    horas_laboratorio = models.IntegerField(u'horas de laboratorio', default=0)
    horas_taller = models.IntegerField(u'Horas de Taller', default=0)
    horas_ayudantia = models.IntegerField(u'Horas de Ayudantía', default=0)

    def __str__ (self):
        return ("%s del %s")%(self.nombre, self.plan.nombre)


class Departamento(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(u'Descripción', max_length=200, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Profesor(models.Model):
    nombre = models.CharField(max_length=100)
    departamento = models.ForeignKey(Departamento)
    rut = models.CharField(u'RUT', max_length=12, default='')
    correo = models.EmailField('Correo Electrónico', max_length=100, default='')

    def __str__(self):
        return self.nombre


class Anio(models.Model):
    nombre = models.CharField(max_length=4)

    class Meta:
        ordering = ["-nombre"]

    def __str__(self):
        return self.nombre


class Periodo(models.Model):
    nombre = models.CharField(max_length=50)
    anio = models.ForeignKey(Anio, null=True)

    class Meta:
        ordering = ["-nombre"]


    def __str__(self):
        return "%s del año %s"%(self.nombre,
                                self.anio.nombre)


class Bloque(models.Model):
    nombre = models.IntegerField(validators=[MaxValueValidator(15),
                                        MinValueValidator(1)],
                                default=0,
                                help_text="""<sup>Indique un número entre 1 y 15
                                        para identificar el bloque</sup>""",
                                )
    hora_inicio = models.TimeField(u'Hora Inicio', default="00:00")
    hora_termino = models.TimeField(u'Hora de Termino', default="00:00")


    class Meta:
        ordering = ["nombre"]


    def __str__(self):
        return "número: %(nombre)s "%{"nombre":self.nombre}


class Actividad(models.Model):
    nombre = models.CharField(max_length=50)
    identificador = models.CharField(max_length=1,
                    help_text="<sup>Escriba una letra para identifique la actividad</sup>",
                    default = "",
                    unique = True,
                    )

    def __str__(self):
        return self.nombre


class ModuloEspejo(models.Model):
    # carrera = models.ForeignKey(Carrera, default=None)
    # plan = models.ForeignKey(Plan, default=None)
    modulo = models.ForeignKey(Modulo, default=None)
    espejo = models.ForeignKey(Modulo, related_name='+')

    def __str__(self):
        msj = "El modulo %(modulo)s es espejo de %(espejo)s"%{
                                    "modulo":self.modulo,
                                    "espejo":self.espejo,
                                    }
        return msj

horario/forms.py
from django import forms
from .models import (PeriodoProfesorModulo,
                     ReservaBloqueProtegido,
                     CursosGrupo,
                     )

class PeriodoProfesorModuloForm(forms.ModelForm):

    class Meta:
        model = PeriodoProfesorModulo
        fields = ["periodo",
                "carrera",
                "plan",
                "modulo",
                "profesor",
                ]


class ReservaBloqueProtegidoForm(forms.ModelForm):

    class Meta:
        model = ReservaBloqueProtegido
        fields = ["bloque",
                    "reservado",
                ]


class CursosGrupoForm(forms.ModelForm):

    class Meta:
        model = CursosGrupo
        fields = [#"periodoprofesormodulo",
                    "modulo",
                ]

templates/horario/base_horario.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}

{% endblock %}



{% block content %}


<!-- <div class="message-alert" -->
<!--     style="border-width:3px;background-color:#cae8ca;border-style:solid; -->
<!--     position:fixed;padding:5px;bottom:0;right:0; -->
<!--     max-width:300px;z-index:999"> -->
<!--     This <div> element has position: fixed;</div> -->
<!-- </div> -->


  {% if confirm %}
  <div class="alert alert-info alert-dismissable">
    {{ confirm }}
  </div>
  {% endif %}

  {% if messages %}

  <div class="alert alert-info alert-dismissable">
    {% for message in messages %}
      {{ message }}
    {% endfor %}

  </div>
  {% endif %}


    {% if titulo == 'Asignación Profesor Módulo' %}
      {% include "horario/periodoprofesormodulo.html" %}
    {% endif %}

    {% if titulo == 'Horario' %}
      {% include "horario/horario.html" %}
    {% endif %}

    {% if titulo == 'Listado de Horarios' %}
      {% include "horario/listado_horario.html" %}
    {% endif %}

    {% if titulo == 'Reserva Bloques protegidos Módulo' %}
      {% include "horario/bloqueprotegido.html" %}
    {% endif %}

    {% if titulo == 'Cursos Grupo' %}
      {% include "horario/cursosgrupo.html" %}
    {% endif %}


{% endblock %}

templates/horario/cursosgrupo.html
{% block content %}

<div class="row">
  <div class="col-lg-12">
		<div class="header">
			<h4>{{ titulo|upper }}</h4>
		  <div class="col-lg-11"></div>
		  <div class="col-lg-1">
		    <button class="btn btn-success add">Nuevo</button>
		  </div>
	  </div>
    <div class="col-lg-12"><p></p></div>
  </div>

  <div class="col-lg-12">
    <div class="panel panel-default">
		  <div class="panel-heading">
		    Filtros de búsqueda
		  </div>
		  <div class="panel-body">
        <div class="col-md-2">
          <label class = "control-label" for="carrera">Carrera</label>
        </div>
        <div class="col-lg-10">
          <select class="form-control" id="carrera">
            <option selected value="0">Seleccione una carrera</option>
	          {% for obj in carrera %}
              <option value="{{ obj.id }}">{{ obj.nombre }}</option>
            {% endfor %}
          </select>
          <p></p>
        </div>

		    <div class="col-md-2">
          <label class = "control-label" for="id_periodo">Periodo</label>
        </div>
        <div class="col-lg-10">
	        <select class="form-control" id="periodo">
            <option selected value="0">Seleccione un periodo</option>
		        {% for obj in periodo %}
              <option value="{{ obj.id }}">{{ obj.nombre }}</option>
            {% endfor %}
          </select>
          <p></p>
        </div>
      </div>
    </div>
  </div>


  {% if object_list != None %}

	<div class="col-lg-12">
	  <h4>Resultados</h4>
    <div class="panel-body">
		  <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead class="thead-default">
				  <tr>
		        <th>Modulo</th>
						<th>Plan</th>
		      	<th>Compartido</th>
						<th></th>
						<th></th>
        	</tr>
        </thead>
			  <tbody>
					{% for obj in object_list %}
						<tr>
						  <td>{{ obj.profesor.nombre }}</td>
							<td>{{ obj.modulo.nombre }}</td>
						  <td>{{ obj.modulo.plan.nombre }}</td>
							<td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs edit" data-title="Edit" data-toggle="modal" data-target="#edit" value="{{ obj.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
							<td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs delete" data-title="Delete" data-toggle="modal" data-target="#delete" value="{{ obj.id }}"><span class="glyphicon glyphicon-trash"></span></button></p></td>
						</tr>
					{% endfor %}
					</tbody>
        </table>
                <!-- /.table-responsive -->
      </div>
            <!-- /.panel-body -->
        <!-- </div> -->
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
{% endif%}
<!-- jQuery -->
    <script src="/static/js/ppm-list.js"></script>

{% endblock %}

templates/horario/form.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load bootstrap3 %}

{% load dia_semana %}

{% block title %}

{% endblock %}



{% block content %}
    <fieldset>
        <legend><h4>{{ titulo|upper }}</h4></legend>
    </fieldset>

    <form id="form" role="form" class="form-horizontal" method="post">
        {% csrf_token %}
        {% bootstrap_form form layout="horizontal" %}

        <div id="accordion" role="tablist" aria-multiselectable="true">
          <div class="card">
            <div class="card-header" role="tab" id="headingTwo">
              <h5 class="mb-0">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                  Reserva de Horario
                </a>
              </h5>
            </div>

            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
              C=Clases, A=Ayudantía, S=Seminario, L=Laboratorio, T=Taller, X=Bloque Protegido
                <table width="100%" class="table table-bordered table-hover">
                    <thead class="thead-default">
					            <tr>
					            <th>Día Semana / Bloque</th>
					              {% for obj in bloque_list %}
						            <th id="{{obj.id}}"><center>{{ obj.nombre }}</center></th>
					              {% endfor %}
					            </tr>
				            </thead>
                    <tbody>
                      {% for k, val in horario.items %}
                          <tr>
                            <td id="dia">{{ dia_semana_list|get_item:k }}</td>
                            {% for v in val.values %}
                              {% if v %}
                                {% if v == "X" %}
                                  <td bgcolor="#d9534f" align="center">
                                    <bold>{{v}}</bold>
                                  </td>
                                {% else %}
                                  <td class="change" align="center">{{v}}</td>
                                {% endif %}
                              {% else %}
                                <td class="change" align="center"></td>
                              {% endif %}
                            {% endfor %}
                          </tr>
                      {% endfor %}
                    </tbody>
                </table>
            </div>
          </div>
        </div>
        <p></p>

        {% buttons layout='horizontal'%}
        <!-- <button type="submit" class="btn btn-primary save-addother"><span class="glyphicon glyphicon-save"></span> Guardar y añadir otro</button> -->
        {% if save_addanother %}
        <button type="submit" class="btn btn-primary save-addanother" name="_addanother">
            <span class="glyphicon glyphicon-save"></span>
            Guardar y añadir otro
        </button>
        {% endif%}
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-saved"></span> Guardar</button>
        <button type="reset" class="btn btn-danger reset reset-horario"><span class="glyphicon glyphicon-remove"></span> Cancelar</button>
        {% endbuttons %}
    </form>




    <!-- jQuery -->
    <script src="/static/js/ppm-action.js"></script>
    <script src="/static/js/change-horario.js"></script>
{% endblock %}

templates/horario/form_ppm_horario.html
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingTwo">
      <h5 class="mb-0">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <button type="button" class="btn btn-primary expand-horario"> <span class="glyphicon glyphicon-collapse-down"> </span>
            Reserva de Horario
          </button>
        </a>
      </h5>
    </div>
  </div>
  <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
    C=Clases, A=Ayudantía, S=Seminario, L=Laboratorio, T=Taller, X=Bloque Protegido
    <table width="100%" class="table table-bordered table-hover">
      <thead class="thead-default">
		    <tr>
			    <th>Día Semana / Bloque</th>
				  {% for obj in bloque_list %}
		        <th id="{{obj.id}}"><center>{{ obj.nombre }}</center></th>
			    {% endfor %}
			  </tr>
			</thead>
      <tbody>
        {% for k, val in horario.items %}
          <tr>
            <td id="dia">{{ dia_semana_list|get_item:k }}</td>
            {% for v in val.values %}
             {% if v %}
               {% if v == "X" %}
                 <td bgcolor="#d9534f" align="center">
                   <bold>{{v}}</bold>
                 </td>
               {% else %}
                 <td class="change" align="center">{{v}}</td>
               {% endif %}
             {% else %}
               <td class="change" align="center"></td>
             {% endif %}
           {% endfor %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

templates/horario/horario.html
{% block content %}

<div class="row">

  <div class="col-lg-12" id="_appendHere">
		<div class="header">
		  <p></p>
		  <h1>{{ titulo }}</h1>
		  <div class="col-lg-12">
		    <p></p>
		    <select class="form-control" id="periodo" name="periodo"></select>
		    <p></p>
		    <select class="form-control" id="carrera" name="carrera"></select>
      </div>
		</div>
	</div>
  <!-- /.col-lg-12 -->


  {% for key, value in dia_semana.items %}
    <div class="col-lg-12">
      <p></p>
      C=Clases, A=Ayudantía, S=Seminario, L=Laboratorio, T=Taller
    </div>
	  <div class="col-lg-12">
		  <div class="panel panel-default">
			  <div class="panel-heading">
			    {{ value }}
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
		      <table width="100%" class="table table-striped table-bordered table-hover table-horario" id= "{{ key }}">
            <thead class="thead-default">
						  <tr>
						    <th class="profesor-header" id="nombre">Profesor</th>
		        	  <th class="modulo-header-{{key}}" id="modulo">Modulo</th>
						    <th class="plan-header-{{key}}" id="plan">Plan</th>
						    <th class="semestre-header-{{key}}" id="semestre">Semestre</th>
						    {% for obj in bloque_list %}
						      <th width=33px> <center>{{obj.nombre}}</center></th>
						    {% endfor %}
          		</tr>
          	</thead>
			      <tbody>
					    {% for x, y in horario.items %}
					      <tr>
					        <td name={{x.profesor.id}}>{{x.profesor.nombre}}</td>
					        {% if x.compartido %}
					          <td name ={{x.modulo.id}}>{{cursos_grupo|get_cursos_grupo:x.modulo.id}}</td>
					        {% else %}
					          <td name ={{x.modulo.id}}>{{x.modulo.nombre}}</td>
					        {% endif %}
					        <td name={{x.modulo.plan.id}}>{{x.modulo.plan.nombre}}</td>
					        <td>{{x.modulo.semestre.nombre}}</td>
					        {% for z, a in y.items %}
					          {% if z == key %}
					            {% for b in a.values %}
					              {% if b %}
					                <td class="change-horario" align="center">{{b}}</td>
					              {% else %}
					                <td class="change-horario" align="center"></td>
					              {% endif %}
					            {% endfor %}
					          {% endif %}
					        {% endfor %}
					      </tr>
					    {% endfor %}
					  </tbody>
          </table>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
        <!-- /.panel panel-default -->
  </div>
    <!-- /.col-lg-12 -->
{% endfor %}
</div>
<!-- jQuery -->

    <script src="/static/js/horario.js"></script>
    <script src="/static/js/change-horario.js"></script>

{% endblock %}

templates/horario/periodoprofesormodulo.html
{% block content %}

<div class="row">

    <div class="col-lg-12">
		<div class="header">
			<h4>{{ titulo|upper }}</h4>
		    <div class="col-lg-11"></div>
		    <div class="col-lg-1">
		        <button class="btn btn-success add">Nuevo</button>
		    	<br></br>
		    </div>
	    </div>
    </div>


    <div class="col-lg-12">
        <div class="panel panel-default">
		    <div class="panel-heading">
		        Filtros de búsqueda
		    </div>
		    <div class="panel-body">

                <div class="col-md-2">
                    <label class = "control-label" for="carrera">Carrera</label>
                </div>
                <div class="col-lg-10">
                    <select class="form-control" id="carrera">
                        <option selected value="0">Seleccione una carrera</option>
	                        {% for obj in carrera %}
                                <option value="{{ obj.id }}">{{ obj.nombre }}</option>
                            {% endfor %}
                    </select>
                    <p></p>
                </div>


                <div class="col-md-2">
                    <label class = "control-label" for="id_periodo">Periodo</label>
                </div>
                <div class="col-lg-10">
	                <select class="form-control" id="periodo">
                        <option selected value="0">Seleccione un periodo</option>
		                    {% for obj in periodo %}
                                <option value="{{ obj.id }}">{{ obj.nombre }}</option>
                            {% endfor %}
                    </select>
                    <p></p>
                </div>

                <div class="col-md-2">
                    <label class = "control-label" for="id_plan">Plan</label>
                </div>
                <div class="col-lg-10">
	                <select class="form-control" id="plan">
                        <option selected value="0">Seleccione un plan</option>
		                    {% for obj in plan %}
                                <option value="{{ obj.id }}">{{ obj.nombre }}</option>
                            {% endfor %}
                    </select>
                    <p></p>
                </div>

            </div>
        </div>
    </div>


    {% if object_list != None %}

	<div class="col-lg-12">
		<!-- <div class="panel panel-default"> -->
		<!-- 	<div class="panel-heading"> -->
            	<!-- {{ titulo }} -->
			    Resultado
            <!-- </div> -->
        	<!-- /.panel-heading -->
            <div class="panel-body">
		    	<!-- <table width="100%" class="table table-sm"> -->
		    	<table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead class="thead-default">
						<tr>
		      				<th>Periodo</th>
						    <th>Nombre</th>
		      				<th>Modulo</th>
						    <th>Plan</th>
							<th></th>
							<th></th>
        				</tr>
        			</thead>
					<tbody>
					{% for obj in object_list %}
						<tr>
							<td>{{ obj.periodo }}</td>
						    <td>{{ obj.profesor.nombre }}</td>
							<td>{{ obj.modulo.nombre }}</td>
						    <td>{{ obj.modulo.plan.nombre }}</td>
							<td><p data-placement="top" data-toggle="tooltip" title="Edit"><button class="btn btn-primary btn-xs edit" data-title="Edit" data-toggle="modal" data-target="#edit" value="{{ obj.id }}" ><span class="glyphicon glyphicon-pencil"></span></button></p></td>
							<td><p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs delete" data-title="Delete" data-toggle="modal" data-target="#delete" value="{{ obj.id }}"><span class="glyphicon glyphicon-trash"></span></button></p></td>
						</tr>
					{% endfor %}
					</tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        <!-- </div> -->
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->


    {% endif%}
<!-- jQuery -->
    <script src="/static/js/ppm-list.js"></script>

{% endblock %}